### ISSUE TITLE
[라벨링] 스크린샷 노출 시 이슈

### ISSUE THREAD

**Issue by HeoJiin** [Nexters/Labelary-iOS#48]
[수행]
1. 라벨링 화면 진입
2. 라벨링 넘겨서 다음 스크린샷 노출

[기대효과]
1. 현재 노출 할떄 세로로 커지는 모션을 취하고 있어서 그냥 노출 되는것이 좋을 것 같아요!
2. 스크린샷을 왼쪽으로 넘겼을 때 다른 이미지가 깜박하면서 나오는 경우가 있눈데 이부분 없애주시면 좋을것같아요!

[비고]
제가 스크린샷 수가 6379개인데 12756이 뜨는데 이것 좀 체크 부탁드립니다 !

https://user-images.githubusercontent.com/88474655/147819381-9142b675-0734-47bd-b669-697576445b57.MP4

**Comment by freemjstudio** [comment]
비고 : 수정했습니다.
