### ISSUE TITLE
[스플래쉬] 스플래쉬 디자인 생략됨 

### ISSUE THREAD

**Issue by HeoJiin** [Nexters/Labelary-iOS#49]
스플래쉬 디자인이 생략된거 같아서 [이렇게](https://www.figma.com/file/nsXjiBbk4BOMSIQJFr9vfH/%EB%84%A5%EC%8A%A4%ED%84%B0%EC%A6%88?node-id=2640%3A58560) 넣어주세용 !

![IMG_1452](https://user-images.githubusercontent.com/88474655/147819569-ac8de7f5-695f-41b6-98d0-cf90ba31e1eb.PNG)

**Comment by freemjstudio** [comment]
이거 넣어서 제 기기에서는 실행되는데 이상하네요 ㅠ 다른 분들도 어떻게 나오는지 봐야할듯..!

**Comment by DaJeongYoon** [comment]
전 디자인은 다 나오는데! 컨텐츠(버튼, 텍스트) 위치값이 잘못 나와요ㅠ 
![IMG_3723](https://user-images.githubusercontent.com/94967459/147851025-65f86dd1-6c72-4afb-be7a-48150340e929.PNG)

**Comment by freemjstudio** [comment]
padding 값을 수정했습니다
