### ISSUE TITLE
[홈] 최근순 스크린샷 화면 > 선택 기능 활성화 시

### ISSUE THREAD

**Issue by HeoJiin** [Nexters/Labelary-iOS#50]
[수행]
1. 최근순 스크린샷 진입
2. 선택 선택,
3. 사진 선택
4. 뒤로가기 -> 홈 진입
5. 다시 최근순 스크린샷 진입

[기대효과]
1. 스크린샷 정렬을 최근순으로 할 수 있나요? 가장 과거의 것이 먼저 오는것 같구용, 첫번째 사진은 처음으로 라벨링 한건데 정렬에 영향이 가는거 같아요!
2. 선택 기능 on 했을때 사진을 선택하면 선택이 되었으면 좋겠습니다. 선택 아이콘만 선택했을 때선택되는게 불편한 것 같아요!
3. 선택을 활성화 시키고 홈으로 진입 시 선택 기능이 비활성화 되었으면 좋겠습니다.

https://user-images.githubusercontent.com/88474655/147820072-4c5ff439-f2a9-47cf-8bdb-611285213e4b.MP4

https://user-images.githubusercontent.com/88474655/147820023-5acc9fb3-3b89-41df-b6b2-960a8ee059f6.MP4

**Comment by freemjstudio** [comment]
1. 스크린샷 정렬을 최근순으로 할 수 있나요? 가장 과거의 것이 먼저 오는것 같구용, 첫번째 사진은 처음으로 라벨링 한건데 정렬에 영향이 가는거 같아요! 

- [ ] 

2. 선택 기능 on 했을때 사진을 선택하면 선택이 되었으면 좋겠습니다. 선택 아이콘만 선택했을 때선택되는게 불편한 것 같아요! 

- [ ] 

3. 선택을 활성화 시키고 홈으로 진입 시 선택 기능이 비활성화 되었으면 좋겠습니다.

- [ ]

**Comment by freemjstudio** [comment]
1, 2 ,3 수정했습니다
