### ISSUE TITLE
[홈] 최근 순 스크린샷에서 사진 삭제 시 

### ISSUE THREAD

**Issue by HeoJiin** [Nexters/Labelary-iOS#51]
[수행]
사진 선택 후 삭제함

[기대효과]
1. 사진 선택 후 사진 선택시 바로 삭제되지 않게 [이렇게 ](https://www.figma.com/file/nsXjiBbk4BOMSIQJFr9vfH/%EB%84%A5%EC%8A%A4%ED%84%B0%EC%A6%88?node-id=1667%3A88)시스템 팝업을 노출시켜주세요!
2. 스크린샷이 삭제된 후 홈 리스트내에서는 그대로 노출되는거 같아요! 그것도 반영을 해주시면 좋겟습니다 ! 

https://user-images.githubusercontent.com/88474655/147820347-882958ac-485c-4d7c-90e3-837ea5e233ea.MP4

**Comment by freemjstudio** [comment]
1. 레이블러리 앱 뿐만 아니라 엘범 안에서도 삭제되도록 할지 안할지 정해야 될것 같아용
2. 해결
