### ISSUE TITLE
[라벨링] 라벨링 메인페이지 디자인 수정

### ISSUE THREAD

**Issue by DaJeongYoon** [Nexters/Labelary-iOS#57]
여러 이슈가 있어서 이미지에 넘버링 같이 넣었습니당!
01. 제 앨범 내에는 스크린샷이 4024개가 있는데 해당 위치에 숫자 반영이 잘못되어있는 것 같아요. + 텍스트 위치가 아래로 내려감
02. 스크린샷 위치가 아래로 내려갔어요
03. 버튼 그림자가 잘못 들어간 것 같아요.
04. 탭 바 백 높이 50px로 안들어간 것 같아요!

![IMG_3721](https://user-images.githubusercontent.com/94967459/147851126-d60e30c1-a6eb-4780-bbaf-bf0d4775ed7e.PNG)
@ @

**Comment by DaJeongYoon** [comment]
버튼 그림자가 현재 이렇게 들어가있어요!
![IMG_3714](https://user-images.githubusercontent.com/94967459/147851790-88c787d4-57a3-4d1c-b1da-de7e8c974f2d.PNG)

**Comment by freemjstudio** [comment]
1 제 앨범 내에는 스크린샷이 4024개가 있는데 해당 위치에 숫자 반영이 잘못되어있는 것 같아요. + 텍스트 위치가 아래로 내려감
-> 수정완료
2 스크린샷 위치가 아래로 내려갔어요
3 버튼 그림자가 잘못 들어간 것 같아요. -> 수정완료 
4 탭 바 백 높이 50px로 안들어간 것 같아요!
