### ISSUE TITLE
[라벨링] 스와이프 제스쳐 디자인 수정

### ISSUE THREAD

**Issue by DaJeongYoon** [Nexters/Labelary-iOS#58]
1-[나중에 하기]_레드로 dim처리된 부분이 스크린샷 크기랑 조금 안맞는 것 같아요ㅜㅜ+아이콘이 찌그러졌네용ㅜㅜ

![IMG_3702](https://user-images.githubusercontent.com/94967459/147851455-aa9dcb7f-ddc3-423a-9383-d4b3d75f227a.PNG)

2-[라벨링하기]_블루 dim하고 아이콘 반영이 안되어있어요!

![IMG_3704](https://user-images.githubusercontent.com/94967459/147851512-d849d5ed-d461-45f9-8d8d-851734c954f1.PNG)

**Comment by freemjstudio** [comment]
1 -> 크기 조절 완료 
2 -> 반영했습니다
