### ISSUE TITLE
[라벨링] 라벨없음 화면_디자인 수정

### ISSUE THREAD

**Issue by DaJeongYoon** [Nexters/Labelary-iOS#59]
좀 전에 스와이프했던 스크린샷이 기울어진 채로 뒤에 유지되고
dim처리된 후 그 위에 컴포넌트들이 올라와야할 것 같습니당ㅜㅜ
![IMG_3705](https://user-images.githubusercontent.com/94967459/147851578-0715e243-a14b-4e6a-8572-e529547134f5.PNG)

**Comment by DaJeongYoon** [comment]
이 프로토타이핑 영상 확인하시면 될 것 같아요!
https://user-images.githubusercontent.com/94967459/147851749-b82e36ca-34cd-4970-907b-eabe119260f4.mp4

**Comment by freemjstudio** [comment]
다른 버그들 고친 이후에 해보겠습니다.. 시간이 좀 걸릴것 같아요
