### ISSUE TITLE
[라벨링] 라벨링 생성_디자인 수정

### ISSUE THREAD

**Issue by DaJeongYoon** [Nexters/Labelary-iOS#60]
1. 컴포넌트(텍스트, navi, 버튼)들이 양옆 마진 20px로 반영이 안되었어요!
2. navi 바 라벨생성 텍스트 중앙정렬로 수정해야할 것 같아용ㅜㅜ 
  (앗 그리고 제 핸드폰에서는 status bar가 다 블랙으로 나오는데 확인 부탁드립니다!)
3. 텍스트'라벨명'-라벨명, '라벨컬러 선택'-라벨 컴포넌트끼리 간격이 잘못들어간것 같아요!
  
![IMG_3725](https://user-images.githubusercontent.com/94967459/147852425-43fe1a50-841e-4c35-9c55-a89b37c96533.PNG)

1. 라벨 텍스트 다 작성 후, 한번에 지울 수 있는 x 버튼 추가해야할 것 같아요!

![IMG_3724](https://user-images.githubusercontent.com/94967459/147852369-2f5b75da-c5e4-478b-bd12-135f92528d30.PNG)

**Comment by freemjstudio** [comment]
1 컴포넌트(텍스트, navi, 버튼)들이 양옆 마진 20px로 반영이 안되었어요!
2navi 바 라벨생성 텍스트 중앙정렬로 수정해야할 것 같아용ㅜㅜ
(앗 그리고 제 핸드폰에서는 status bar가 다 블랙으로 나오는데 확인 부탁드립니다!)
-> 수정 완료 
3 텍스트'라벨명'-라벨명, '라벨컬러 선택'-라벨 컴포넌트끼리 간격이 잘못들어간것 같아요!
