### ISSUE TITLE
[스플래쉬] 앱 설치 후 첫 실행이 아니어도 계속 노출되는 이슈

### ISSUE THREAD

**Issue by haeunjin** [Nexters/Labelary-iOS#66]
[수행]
1. 앱 설치 후 첫 실행 후 앱 종료
2. 앱 다시 실행

[기대결과]
첫 실행시에만 스플래쉬가 나옴

[실제결과]
첫 실행 이후에도 실행할 때마다 스플래쉬가 나옴

**Comment by freemjstudio** [comment]
반영했습니다 !
