### ISSUE TITLE
[status bar] 색상 변경

### ISSUE THREAD

**Issue by haeunjin** [Nexters/Labelary-iOS#75]
status bar 색상 화이트로 변경 부탁드려요.

**Comment by freemjstudio** [comment]
혹시 status bar가  어디있는 걸 말하는걸까요 ..??

**Comment by haeunjin** [comment]
![7A7725C5-06A3-4BE6-AE7A-F3F1D8799F5E](https://user-images.githubusercontent.com/94969930/150037451-a9613ea6-16c0-4e28-9229-bd580d15120c.jpeg)
이 부분이요! @freemjstudio

**Comment by freemjstudio** [comment]
다크모드 대응해서 폰트 색상 흰색으로 변경했습니다
